CREATE Database Auction1
GO
USE Auction1

GO
CREATE TABLE _User
(
	ID INT IDENTITY PRIMARY KEY,
	_UserName VARCHAR(1000) NOT NULL,
	_PassWord vARCHAR(1000) NOT NULL,
	Phone VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	MangerUser INT  FOREIGN KEY REFERENCES _User(ID)
)
CREATE TABLE Category
(
	ID INT IDENTITY PRIMARY KEY,
	_Name VARCHAR(1000) NOT NULL,
)
CREATE TABLE Post
(
	ID INT IDENTITY PRIMARY KEY,
	UserID INT  FOREIGN KEY REFERENCES _User(ID),
	_Status BIT NOT NULL,
)
CREATE TABLE Product
(
	ID INT IDENTITY PRIMARY KEY,
	_Name VARCHAR(1000) NOT NULL,
	CategoryId INT  FOREIGN KEY REFERENCES Category(ID),
	urlImg VARCHAR(1000),
	describe VARCHAR(1000),
	Price DECIMAL(15,3)  NOT NULL,-- TRUONG NAY LUU THONG TIN GIA KHOI DIEM 
)
ALTER TABLE [Product]
ADD CONSTRAINT FK_ID_Post FOREIGN KEY([ID]) 
    REFERENCES [Post]([ID]);
CREATE TABLE PhienDauGia
(
	ID INT IDENTITY PRIMARY KEY,
	FixedPrice DECIMAL(15,3) NOT NULL,
	StartTime DATETime NOT NULL -- THOI GIAN BAT DAU PHIEN DAU GIA
)
CREATE TABLE ChiTietPhienDauGia
(
	ID INT IDENTITY PRIMARY KEY,
	UserID INT  FOREIGN KEY REFERENCES _User(ID),
	IdPhienDauGia  INT  FOREIGN KEY REFERENCES PhienDauGia(ID),
	Price DECIMAL(15,3) NOT NULL,
)
